# Generated by Django 6.0.1 on 2026-03-02 09:27

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="XRayAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Chest X-ray image file (JPEG, PNG, DICOM).",
                        upload_to="xrays/%Y/%m/%d/",
                        verbose_name="X-ray Image",
                    ),
                ),
                (
                    "class_probs",
                    models.JSONField(
                        help_text="Classification probabilities per class.",
                        verbose_name="Class Probabilities",
                    ),
                ),
                (
                    "pred_label",
                    models.CharField(
                        help_text="Predicted class label.",
                        max_length=100,
                        verbose_name="Predicted Label",
                    ),
                ),
                (
                    "findings",
                    models.JSONField(
                        help_text="Derived findings from heatmap analysis.",
                        verbose_name="Findings",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xray_analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "X-ray Analysis",
                "verbose_name_plural": "X-ray Analyses",
                "db_table": "xray_analysis",
            },
        ),
        migrations.CreateModel(
            name="XRayEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_id", models.CharField(max_length=255, verbose_name="Image ID")),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1024,
                        help_text="1024-dimensional embedding",
                        null=True,
                        verbose_name="Vector Embedding",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
            ],
            options={
                "verbose_name": "X-ray Embedding",
                "verbose_name_plural": "X-ray Embeddings",
                "db_table": "xray_embeddings",
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="xray_embedding_hnsw_idx",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
