# Generated by Django 6.0.1 on 2026-03-03 03:44

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="xrayanalysis",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1024,
                help_text="1024-dimensional embedding",
                null=True,
                verbose_name="Vector Embedding",
            ),
        ),
    ]
