# Generated by Django 6.0.1 on 2026-03-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0002_xrayanalysis_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="xrayanalysis",
            name="heatmap_base64",
            field=models.TextField(
                blank=True,
                help_text="Base64 encoded PNG of the Grad-CAM heatmap.",
                null=True,
                verbose_name="Heatmap Base64",
            ),
        ),
    ]
