# Generated by Django 6.0.1 on 2026-01-14 08:21

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0002_alter_customer_address"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.CreateModel(
            name="ChatbotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Configuration Key"
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="Configuration value (can be string, number, object, etc.)",
                        verbose_name="Value",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this configuration controls",
                        verbose_name="Description",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Chatbot Configuration",
                "verbose_name_plural": "Chatbot Configurations",
                "db_table": "chatbot_config",
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Session ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated from first message or user-defined",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="authentication.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "db_table": "chat_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data like retrieved documents, tokens used, etc.",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.chatsession",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=768,
                        help_text="768-dimensional embedding from text-embedding-004",
                        null=True,
                        verbose_name="Vector Embedding",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("symptom", "Symptoms"),
                            ("aetiologies", "Aetiologies"),
                            ("diagnose_and_treaty", "Diagnosis and Treatment"),
                            ("risk", "Risk Factors"),
                            ("living_and_preventive", "Living and Prevention"),
                            ("general", "General Information"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Section Type",
                    ),
                ),
                (
                    "index_type",
                    models.CharField(
                        choices=[
                            ("A", "Summary Index"),
                            ("B", "Detail Index"),
                            ("C", "Title Index"),
                        ],
                        default="B",
                        max_length=1,
                        verbose_name="Index Type",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source file or dataset name",
                        max_length=255,
                        verbose_name="Source",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Medical Document",
                "verbose_name_plural": "Medical Documents",
                "db_table": "medical_document",
                "indexes": [
                    models.Index(fields=["title"], name="medical_doc_title_5f6743_idx"),
                    models.Index(
                        fields=["section_type"], name="medical_doc_section_802e54_idx"
                    ),
                    models.Index(
                        fields=["index_type"], name="medical_doc_index_t_8dcc6a_idx"
                    ),
                ],
            },
        ),
    ]
