# Generated by Django 6.0.1 on 2026-01-20 07:30

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Configuration Key"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rag", "RAG Pipeline"),
                            ("model", "Model Settings"),
                            ("rate_limit", "Rate Limits"),
                            ("feature", "Feature Flags"),
                            ("processing", "Text Processing"),
                        ],
                        default="rag",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="Configuration value (can be string, number, object, etc.)",
                        null=True,
                        verbose_name="Value",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this configuration controls",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this configuration is currently in use",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Chatbot Configuration",
                "verbose_name_plural": "Chatbot Configurations",
                "db_table": "chatbot_config",
                "indexes": [
                    models.Index(
                        fields=["category"], name="chatbot_con_categor_f31315_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="chatbot_con_is_acti_09ff4e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Session ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated from first message or user-defined",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "max_messages",
                    models.PositiveIntegerField(
                        default=50, help_text="Max messages to keep in context window"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "db_table": "chat_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                            ("tool", "Tool"),
                        ],
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time taken to generate this response",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data like retrieved documents, tokens used, etc.",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.chatsession",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=768,
                        help_text="768-dimensional embedding from text-embedding-004",
                        null=True,
                        verbose_name="Vector Embedding",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("symptom", "Symptoms"),
                            ("aetiologies", "Aetiologies"),
                            ("diagnose_and_treaty", "Diagnosis and Treatment"),
                            ("risk", "Risk Factors"),
                            ("living_and_preventive", "Living and Prevention"),
                            ("general", "General Information"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Section Type",
                    ),
                ),
                (
                    "index_type",
                    models.CharField(
                        choices=[
                            ("A", "Summary Index"),
                            ("B", "Detail Index"),
                            ("C", "Title Index"),
                        ],
                        default="B",
                        max_length=1,
                        verbose_name="Index Type",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source file or dataset name",
                        max_length=255,
                        verbose_name="Source",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Medical Document",
                "verbose_name_plural": "Medical Documents",
                "db_table": "medical_document",
                "indexes": [
                    models.Index(fields=["title"], name="medical_doc_title_5f6743_idx"),
                    models.Index(
                        fields=["section_type"], name="medical_doc_section_802e54_idx"
                    ),
                    models.Index(
                        fields=["index_type"], name="medical_doc_index_t_8dcc6a_idx"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="embedding_hnsw_idx",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_style",
                    models.CharField(
                        choices=[
                            ("concise", "Concise"),
                            ("balanced", "Balanced"),
                            ("detailed", "Detailed"),
                        ],
                        default="balanced",
                        help_text="Preferred level of detail in responses",
                        max_length=20,
                        verbose_name="Response Style",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="vi",
                        help_text="Preferred response language (vi, en)",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "max_context_messages",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Maximum messages to keep in conversation context",
                        verbose_name="Max Context Messages",
                    ),
                ),
                (
                    "enable_medical_disclaimer",
                    models.BooleanField(
                        default=True,
                        help_text="Show medical disclaimer in responses",
                        verbose_name="Enable Medical Disclaimer",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preference",
            },
        ),
    ]
