# Generated by Django 6.0.1 on 2026-01-22 05:03

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicaldocument",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1024,
                help_text="1024-dimensional embedding from Qwen/Qwen3-Embedding-0.6B",
                null=True,
                verbose_name="Vector Embedding",
            ),
        ),
    ]
