# Generated by Django 6.0.1 on 2026-01-15 03:15

import django.db.models.deletion
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_customer_address"),
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_style",
                    models.CharField(
                        choices=[
                            ("concise", "Concise"),
                            ("balanced", "Balanced"),
                            ("detailed", "Detailed"),
                        ],
                        default="balanced",
                        help_text="Preferred level of detail in responses",
                        max_length=20,
                        verbose_name="Response Style",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="vi",
                        help_text="Preferred response language (vi, en)",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "max_context_messages",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Maximum messages to keep in conversation context",
                        verbose_name="Max Context Messages",
                    ),
                ),
                (
                    "enable_medical_disclaimer",
                    models.BooleanField(
                        default=True,
                        help_text="Show medical disclaimer in responses",
                        verbose_name="Enable Medical Disclaimer",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preference",
            },
        ),
        migrations.AddField(
            model_name="chatbotconfig",
            name="category",
            field=models.CharField(
                choices=[
                    ("rag", "RAG Pipeline"),
                    ("model", "Model Settings"),
                    ("rate_limit", "Rate Limits"),
                    ("feature", "Feature Flags"),
                    ("processing", "Text Processing"),
                ],
                default="rag",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="chatbotconfig",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this configuration is currently in use",
                verbose_name="Is Active",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="response_time_ms",
            field=models.PositiveIntegerField(
                blank=True, help_text="Time taken to generate this response", null=True
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="max_messages",
            field=models.PositiveIntegerField(
                default=50, help_text="Max messages to keep in context window"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                    ("tool", "Tool"),
                ],
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotconfig",
            index=models.Index(
                fields=["category"], name="chatbot_con_categor_f31315_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotconfig",
            index=models.Index(
                fields=["is_active"], name="chatbot_con_is_acti_09ff4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocument",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="embedding_hnsw_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatbot_preference",
                to="authentication.customer",
                verbose_name="Customer",
            ),
        ),
    ]
