# Generated by Django 6.0.1 on 2026-01-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_add_user_preference_and_config_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotconfig",
            name="value",
            field=models.JSONField(
                help_text="Configuration value (can be string, number, object, etc.)",
                null=True,
                verbose_name="Value",
            ),
        ),
    ]
