# Generated by Django 6.0.1 on 2026-01-23 05:17

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("chatbot", "0002_alter_medicaldocument_embedding_dimension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIntake",
            fields=[
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="intake",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
                (
                    "disease_name",
                    models.CharField(
                        blank=True,
                        help_text="Current disease or condition being discussed",
                        max_length=200,
                        null=True,
                        verbose_name="Disease Name",
                    ),
                ),
                (
                    "symptoms",
                    models.JSONField(
                        default=list,
                        help_text="List of symptoms the patient is experiencing",
                        verbose_name="Positive Symptoms",
                    ),
                ),
                (
                    "symptoms_negated",
                    models.JSONField(
                        default=list,
                        help_text="List of symptoms the patient explicitly does NOT have",
                        verbose_name="Negated Symptoms",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Patient age in years",
                        null=True,
                        verbose_name="Age",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="Sex",
                    ),
                ),
                (
                    "pregnancy_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("unknown", "Unknown"),
                            ("not_applicable", "N/A"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Pregnancy Status",
                    ),
                ),
                (
                    "location_country",
                    models.CharField(
                        blank=True,
                        help_text="Patient's country of residence",
                        max_length=100,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "chronic_conditions",
                    models.JSONField(
                        default=list,
                        help_text="Long-term medical conditions",
                        verbose_name="Chronic Conditions",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        default=list,
                        help_text="Known allergies",
                        verbose_name="Allergies",
                    ),
                ),
                (
                    "onset_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days since symptoms started",
                        null=True,
                        verbose_name="Onset Days",
                    ),
                ),
                (
                    "meds",
                    models.JSONField(
                        default=list,
                        help_text="Medications currently being taken",
                        verbose_name="Current Medications",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "User Intake",
                "verbose_name_plural": "User Intakes",
                "db_table": "user_intake",
            },
        ),
        migrations.AlterField(
            model_name="medicaldocument",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1024,
                help_text="1024-dimensional embedding",
                null=True,
                verbose_name="Vector Embedding",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("customer",),
                name="one_active_session_per_customer",
            ),
        ),
    ]
