# Generated by Django 6.0.1 on 2026-03-12 20:38
# Custom migration: clear existing 1024d embeddings before altering to 768d

import pgvector.django.vector
from django.db import migrations


def clear_embeddings(apps, schema_editor):
    """Set all existing embeddings to NULL so pgvector can alter dimensions."""
    MedicalDocument = apps.get_model("chatbot", "MedicalDocument")
    count = MedicalDocument.objects.exclude(embedding=None).update(embedding=None)
    if count:
        print(f"\n  ⚠️  Cleared {count} existing 1024d embeddings (will need re-embedding)")


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_userintake_alter_medicaldocument_embedding_and_more"),
    ]

    operations = [
        # Step 1: Clear existing 1024d embeddings
        migrations.RunPython(
            clear_embeddings,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 2: Alter column to 768 dimensions
        migrations.AlterField(
            model_name="medicaldocument",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=768,
                help_text="768-dimensional embedding (text-embedding-004)",
                null=True,
                verbose_name="Vector Embedding",
            ),
        ),
    ]
