# Generated by Django 6.0.1 on 2026-03-31 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_alter_medicaldocument_embedding_to_768d"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicaldocument",
            name="embedding_provider",
            field=models.CharField(
                default="transformers",
                help_text="Provider used to generate this embedding: transformers, gemini, tei",
                max_length=50,
                verbose_name="Embedding Provider",
            ),
        ),
        migrations.AddField(
            model_name="medicaldocument",
            name="last_reembedded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this document was last re-embedded",
                null=True,
                verbose_name="Last Re-embedded At",
            ),
        ),
        migrations.CreateModel(
            name="EmbeddingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("reembed_selected", "Re-embed Selected Documents"),
                            ("reembed_section", "Re-embed by Section"),
                            ("reembed_missing", "Re-embed Missing Embeddings"),
                            ("change_provider", "Change Embedding Provider"),
                            ("csv_upload", "CSV Upload"),
                        ],
                        default="reembed_selected",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(default="transformers", max_length=50)),
                (
                    "old_provider",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "section_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("document_ids", models.JSONField(blank=True, default=list)),
                ("total_documents", models.IntegerField(default=0)),
                ("successful_documents", models.IntegerField(default=0)),
                ("failed_documents", models.IntegerField(default=0)),
                ("error_messages", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embedding_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="EmbeddingAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create Document"),
                            ("update", "Update Document"),
                            ("delete", "Delete Document"),
                            ("reembed", "Re-embed Document"),
                            ("bulk_delete", "Bulk Delete"),
                            ("bulk_export", "Bulk Export"),
                            ("bulk_metadata_edit", "Bulk Metadata Edit"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object showing before/after values",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="chatbot.medicaldocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embedding_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "embedding_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="chatbot.embeddingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="medicaldocument",
            name="embedding_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="chatbot.embeddingjob",
                verbose_name="Embedding Job",
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocument",
            index=models.Index(
                fields=["embedding_provider"], name="medical_doc_embeddi_6846d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocument",
            index=models.Index(
                fields=["-last_reembedded_at"], name="medical_doc_last_re_7c9fdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="embeddingjob",
            index=models.Index(
                fields=["status", "-started_at"], name="chatbot_emb_status_0d4cf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="embeddingjob",
            index=models.Index(
                fields=["job_type", "status"], name="chatbot_emb_job_typ_724d1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="embeddingjob",
            index=models.Index(
                fields=["celery_task_id"], name="chatbot_emb_celery__e958da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="embeddingauditlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="chatbot_emb_action_ec423a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="embeddingauditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="chatbot_emb_user_id_d79222_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="embeddingauditlog",
            index=models.Index(
                fields=["document"], name="chatbot_emb_documen_dfa558_idx"
            ),
        ),
    ]
