# Generated by Django 6.0.1 on 2026-04-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_medicaldocument_embedding_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("reembed_selected", "Re-embed Selected Documents"),
                    ("reembed_section", "Re-embed by Section"),
                    ("reembed_missing", "Re-embed Missing Embeddings"),
                    ("change_provider", "Change Embedding Provider"),
                    ("csv_upload", "CSV Upload"),
                    ("url_ingest", "URL Crawl & Embed"),
                ],
                default="reembed_selected",
                max_length=50,
            ),
        ),
    ]
