# Generated by Claude Code on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_alter_embeddingjob_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("reembed_selected", "Re-embed Selected Documents"),
                    ("reembed_section", "Re-embed by Section"),
                    ("reembed_missing", "Re-embed Missing Embeddings"),
                    ("change_provider", "Change Embedding Provider"),
                    ("csv_upload", "CSV Upload"),
                    ("url_ingest", "URL Crawl & Embed"),
                    ("paste_ingest", "Paste Content & Embed"),
                ],
                default="reembed_selected",
                max_length=50,
            ),
        ),
    ]
