# Generated by Django 6.0.1 on 2026-05-19 17:14

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


INDEX_COLLECTION_MODEL = {
    "A": "MedicalDiseaseDocument",
    "B": "MedicalDocumentChunk",
    "C": "MedicalDocumentTitle",
}

INDEX_COLLECTION_TABLE = {
    "A": "medical_documents_disease",
    "B": "medical_documents_chunks",
    "C": "medical_documents_titles",
}


def copy_medical_documents_to_collections(apps, schema_editor):
    medical_document = apps.get_model("chatbot", "MedicalDocument")
    embedding_audit_log = apps.get_model("chatbot", "EmbeddingAuditLog")

    index_collection_by_doc_id = {}
    for document in medical_document.objects.all().iterator():
        index_type = document.index_type or "B"
        model_name = INDEX_COLLECTION_MODEL.get(index_type, "MedicalDocumentChunk")
        collection_model = apps.get_model("chatbot", model_name)
        collection_model.objects.create(
            id=document.id,
            title=document.title,
            content=document.content,
            embedding=document.embedding,
            section_type=document.section_type,
            source=document.source,
            metadata=document.metadata,
            embedding_provider=document.embedding_provider,
            last_reembedded_at=document.last_reembedded_at,
            embedding_job_id=document.embedding_job_id,
            created_at=document.created_at,
            updated_at=document.updated_at,
        )
        index_collection_by_doc_id[document.id] = INDEX_COLLECTION_TABLE.get(
            index_type, "medical_documents_chunks"
        )

    for model_name in INDEX_COLLECTION_MODEL.values():
        collection_model = apps.get_model("chatbot", model_name)
        table_name = collection_model._meta.db_table
        quoted_table_name = schema_editor.connection.ops.quote_name(table_name)
        sql = (
            f"SELECT setval(pg_get_serial_sequence('{table_name}', 'id'), "
            f"COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM {quoted_table_name}"
        )
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(sql)

    for audit_log in embedding_audit_log.objects.exclude(document_id__isnull=True):
        collection_name = index_collection_by_doc_id.get(audit_log.document_id)
        if collection_name:
            audit_log.collection_name = collection_name
            audit_log.save(update_fields=["collection_name"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_alter_embeddingjob_job_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalDiseaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=768,
                        help_text="768-dimensional embedding (text-embedding-004)",
                        null=True,
                        verbose_name="Vector Embedding",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("symptom", "Symptoms"),
                            ("aetiologies", "Aetiologies"),
                            ("diagnose_and_treaty", "Diagnosis and Treatment"),
                            ("risk", "Risk Factors"),
                            ("living_and_preventive", "Living and Prevention"),
                            ("general", "General Information"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Section Type",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source file or dataset name",
                        max_length=255,
                        verbose_name="Source",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "embedding_provider",
                    models.CharField(
                        default="transformers",
                        help_text="Provider used to generate this embedding: transformers, gemini, tei",
                        max_length=50,
                        verbose_name="Embedding Provider",
                    ),
                ),
                (
                    "last_reembedded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this document was last re-embedded",
                        null=True,
                        verbose_name="Last Re-embedded At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Medical Disease Document",
                "verbose_name_plural": "Medical Disease Documents",
                "db_table": "medical_documents_disease",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalDocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=768,
                        help_text="768-dimensional embedding (text-embedding-004)",
                        null=True,
                        verbose_name="Vector Embedding",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("symptom", "Symptoms"),
                            ("aetiologies", "Aetiologies"),
                            ("diagnose_and_treaty", "Diagnosis and Treatment"),
                            ("risk", "Risk Factors"),
                            ("living_and_preventive", "Living and Prevention"),
                            ("general", "General Information"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Section Type",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source file or dataset name",
                        max_length=255,
                        verbose_name="Source",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "embedding_provider",
                    models.CharField(
                        default="transformers",
                        help_text="Provider used to generate this embedding: transformers, gemini, tei",
                        max_length=50,
                        verbose_name="Embedding Provider",
                    ),
                ),
                (
                    "last_reembedded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this document was last re-embedded",
                        null=True,
                        verbose_name="Last Re-embedded At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Medical Document Chunk",
                "verbose_name_plural": "Medical Document Chunks",
                "db_table": "medical_documents_chunks",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalDocumentTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=768,
                        help_text="768-dimensional embedding (text-embedding-004)",
                        null=True,
                        verbose_name="Vector Embedding",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("symptom", "Symptoms"),
                            ("aetiologies", "Aetiologies"),
                            ("diagnose_and_treaty", "Diagnosis and Treatment"),
                            ("risk", "Risk Factors"),
                            ("living_and_preventive", "Living and Prevention"),
                            ("general", "General Information"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Section Type",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source file or dataset name",
                        max_length=255,
                        verbose_name="Source",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "embedding_provider",
                    models.CharField(
                        default="transformers",
                        help_text="Provider used to generate this embedding: transformers, gemini, tei",
                        max_length=50,
                        verbose_name="Embedding Provider",
                    ),
                ),
                (
                    "last_reembedded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this document was last re-embedded",
                        null=True,
                        verbose_name="Last Re-embedded At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Medical Document Title",
                "verbose_name_plural": "Medical Document Titles",
                "db_table": "medical_documents_titles",
                "abstract": False,
            },
        ),
        migrations.RemoveIndex(
            model_name="medicaldocument",
            name="medical_doc_title_5f6743_idx",
        ),
        migrations.RemoveIndex(
            model_name="medicaldocument",
            name="medical_doc_section_802e54_idx",
        ),
        migrations.RemoveIndex(
            model_name="medicaldocument",
            name="medical_doc_index_t_8dcc6a_idx",
        ),
        migrations.RemoveIndex(
            model_name="medicaldocument",
            name="embedding_hnsw_idx",
        ),
        migrations.RemoveIndex(
            model_name="medicaldocument",
            name="medical_doc_embeddi_6846d1_idx",
        ),
        migrations.RemoveIndex(
            model_name="medicaldocument",
            name="medical_doc_last_re_7c9fdd_idx",
        ),
        migrations.RemoveIndex(
            model_name="embeddingauditlog",
            name="chatbot_emb_documen_dfa558_idx",
        ),
        migrations.AddField(
            model_name="embeddingauditlog",
            name="collection_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="embeddingauditlog",
                    name="document",
                ),
                migrations.AddField(
                    model_name="embeddingauditlog",
                    name="document_id",
                    field=models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddIndex(
            model_name="embeddingauditlog",
            index=models.Index(
                fields=["collection_name", "document_id"],
                name="chatbot_emb_collect_5095c5_idx",
            ),
        ),
        migrations.AddField(
            model_name="medicaldiseasedocument",
            name="embedding_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_documents",
                to="chatbot.embeddingjob",
                verbose_name="Embedding Job",
            ),
        ),
        migrations.AddField(
            model_name="medicaldocumentchunk",
            name="embedding_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_documents",
                to="chatbot.embeddingjob",
                verbose_name="Embedding Job",
            ),
        ),
        migrations.AddField(
            model_name="medicaldocumenttitle",
            name="embedding_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_documents",
                to="chatbot.embeddingjob",
                verbose_name="Embedding Job",
            ),
        ),
        migrations.RunPython(copy_medical_documents_to_collections, noop_reverse),
        migrations.RemoveField(
            model_name="medicaldocument",
            name="embedding_job",
        ),
        migrations.AddIndex(
            model_name="medicaldiseasedocument",
            index=models.Index(fields=["title"], name="medical_doc_title_e3d406_idx"),
        ),
        migrations.AddIndex(
            model_name="medicaldiseasedocument",
            index=models.Index(
                fields=["section_type"], name="medical_doc_section_b7db62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldiseasedocument",
            index=models.Index(
                fields=["embedding_provider"], name="medical_doc_embeddi_6bed46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldiseasedocument",
            index=models.Index(
                fields=["-last_reembedded_at"], name="medical_doc_last_re_96481d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldiseasedocument",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="med_disease_hnsw_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocumentchunk",
            index=models.Index(fields=["title"], name="medical_doc_title_f948c5_idx"),
        ),
        migrations.AddIndex(
            model_name="medicaldocumentchunk",
            index=models.Index(
                fields=["section_type"], name="medical_doc_section_c2c086_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocumentchunk",
            index=models.Index(
                fields=["embedding_provider"], name="medical_doc_embeddi_b184bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocumentchunk",
            index=models.Index(
                fields=["-last_reembedded_at"], name="medical_doc_last_re_b78db8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocumentchunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="med_chunks_hnsw_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocumenttitle",
            index=models.Index(fields=["title"], name="medical_doc_title_65eea8_idx"),
        ),
        migrations.AddIndex(
            model_name="medicaldocumenttitle",
            index=models.Index(
                fields=["section_type"], name="medical_doc_section_0cb63c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocumenttitle",
            index=models.Index(
                fields=["embedding_provider"], name="medical_doc_embeddi_726e59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocumenttitle",
            index=models.Index(
                fields=["-last_reembedded_at"], name="medical_doc_last_re_68b667_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocumenttitle",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="med_titles_hnsw_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.DeleteModel(
            name="MedicalDocument",
        ),
    ]
