# Generated by Django 4.2 on 2023-12-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="Address"),
        ),
    ]
