"""
Constants for embedding services.
"""

DEFAULT_EMBEDDING_MODEL = "openai/text-embedding-3-small"
EMBEDDING_PROVIDER_GEMINI = "gemini"
EMBEDDING_PROVIDER_OPENROUTER = "openrouter"
EMBEDDING_PROVIDER_TEI = "tei"
EMBEDDING_PROVIDER_TRANSFORMERS = "transformers"
DEFAULT_EMBEDDING_PROVIDER = EMBEDDING_PROVIDER_TRANSFORMERS

DEFAULT_TRANSFORMERS_MODEL = "Qwen/Qwen3-Embedding-0.6B"
DEFAULT_TRANSFORMERS_INSTRUCTION = (
    "Given a web search query, retrieve relevant passages that answer the query"
)
DEFAULT_OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
DEFAULT_OPENROUTER_MODEL = "text-embedding-3-small"

GOOGLE_API_KEY_ENV_NAME = "GOOGLE_API_KEY"
OPENROUTER_API_KEY_ENV_NAME = "OPENROUTER_API_KEY"
OPENROUTER_BASE_URL_ENV_NAME = "OPENROUTER_BASE_URL"
TEI_ENDPOINT_ENV_NAME = "TEI_ENDPOINT_URL"
TEI_EMBEDDING_ENDPOINT_SUFFIX = "/v1/embeddings"
